site: Roshan-R
url: #yoururl
title: Roshan-R
description: Welcome to my blog
googlewebfonts: Fira+Code:wght@400;500;700
author:
  #twitter: #yourusername
  name: Roshan R Chandar
  avatar:
  email: roshan@cet.ac.in
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: rouge
#highlighter: pygments

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
